apiVersion: apps/v1
kind: Deployment
metadata:
  name: twenty48-deployment
  labels:
      app: twenty48
spec:
  replicas: 2
  selector:
    matchLabels:
      app: twenty48
  template:
    metadata:
      labels:
        app: twenty48
    spec:
      containers:
      - name: twenty48
        image: alexwhen/docker-2048
        ports:
        - containerPort: 80
