apiVersion: apps/v1
kind: Deployment
metadata:
  name: "2048-deployment"
spec:
  selector:
    matchLabels:
      app: twentyfortyeight
  replicas: 5
  template:
    metadata:
      labels:
        app: twentyfortyeight
    spec:
      containers:
        - image: alexwhen/docker-2048
          imagePullPolicy: Always
          name: twentyfortyeight
          ports:
            - containerPort: 80
              protocol: TCP
