apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://git.epam.com/bence_temesvari/devops-academy-2021-2.git
    targetRevision: BenceKiss
    path: sprint12/BenceKiss/on-demand-with-argocd/nginx
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: false
      selfHeal: false